/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t e-model.glb 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    robot: THREE.Mesh
  }
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial
  }
}


export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/e-model.glb') as unknown as GLTFResult
  
  // Modify material properties for reflection/refraction
  materials['Material.004'].metalness = 0.2
  materials['Material.004'].roughness = 0.6
  materials['Material.004'].envMapIntensity = 0.3
  
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={8} decay={2} position={[2.449, 2.919, 3.836]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={8} decay={2} position={[-2.492, 2.919, 3.836]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={4} decay={2} color="#ff0000" position={[2.505, 6.026, -3.262]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={4} decay={2} color="#ff0000" position={[-2.49, 6.026, -3.262]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={4} decay={2} color="#ff0000" position={[0, 6.026, -3.844]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.robot.geometry} material={materials['Material.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/e-model.glb')
