/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TextureEditorImport } from './routes/texture-editor'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TextureEditorRoute = TextureEditorImport.update({
  id: '/texture-editor',
  path: '/texture-editor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/texture-editor': {
      id: '/texture-editor'
      path: '/texture-editor'
      fullPath: '/texture-editor'
      preLoaderRoute: typeof TextureEditorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/texture-editor': typeof TextureEditorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/texture-editor': typeof TextureEditorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/texture-editor': typeof TextureEditorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/texture-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/texture-editor'
  id: '__root__' | '/' | '/texture-editor'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TextureEditorRoute: typeof TextureEditorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TextureEditorRoute: TextureEditorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/texture-editor"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/texture-editor": {
      "filePath": "texture-editor.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
